FROM nginx:latest

# Copy nginx.conf from the host machine to the container's NGINX configuration directory
COPY ./nginx.conf /etc/nginx/nginx.conf

# Ensure SSL certificates are mounted via volumes as specified in docker-compose.yml

